-- Seed the global exercise catalog with the 154 Spanish PRGS exercises.
-- Global rows: source='seed', is_public=true, created_by_trainer=NULL.
-- Idempotent: skips a name that already exists as a seed global row.
-- Run seed_exercises_cleanup.sql BEFORE this file.

insert into public.exercises (name, category, muscle_group, equipment, source, is_public, created_by_trainer)
select v.name, v.category, v.muscle_group,
       case when v.equipment is null then null else array[v.equipment]::text[] end,
       'seed', true, null
from (values
  ('Press banca plano', 'Pecho', 'Pecho', 'Barra'),
  ('Press banca inclinado', 'Pecho', 'Pecho', 'Barra'),
  ('Press banca declinado', 'Pecho', 'Pecho', 'Barra'),
  ('Press inclinado con mancuernas', 'Pecho', 'Pecho', 'Mancuernas'),
  ('Press plano con mancuernas', 'Pecho', 'Pecho', 'Mancuernas'),
  ('Press declinado con mancuernas', 'Pecho', 'Pecho', 'Mancuernas'),
  ('Aperturas con mancuernas', 'Pecho', 'Pecho', 'Mancuernas'),
  ('Aperturas inclinadas con mancuernas', 'Pecho', 'Pecho', 'Mancuernas'),
  ('Pec Deck', 'Pecho', 'Pecho', 'Máquina'),
  ('Press de pecho en máquina', 'Pecho', 'Pecho', 'Máquina'),
  ('Press convergente de pecho', 'Pecho', 'Pecho', 'Máquina'),
  ('Fondos en paralelas', 'Pecho', 'Pecho', 'Peso corporal'),
  ('Fondos asistidos', 'Pecho', 'Pecho', 'Máquina'),
  ('Cruce de poleas alto', 'Pecho', 'Pecho', 'Poleas'),
  ('Cruce de poleas medio', 'Pecho', 'Pecho', 'Poleas'),
  ('Cruce de poleas bajo', 'Pecho', 'Pecho', 'Poleas'),
  ('Pullover con mancuerna', 'Pecho', 'Pecho', 'Mancuerna'),
  ('Press banca con agarre cerrado', 'Pecho', 'Pecho', 'Barra'),
  ('Dominadas pronadas', 'Espalda', 'Espalda', 'Peso corporal'),
  ('Dominadas supinas', 'Espalda', 'Espalda', 'Peso corporal'),
  ('Dominadas neutras', 'Espalda', 'Espalda', 'Peso corporal'),
  ('Jalón al pecho', 'Espalda', 'Espalda', 'Polea'),
  ('Jalón agarre estrecho', 'Espalda', 'Espalda', 'Polea'),
  ('Jalón unilateral', 'Espalda', 'Espalda', 'Polea'),
  ('Remo con barra', 'Espalda', 'Espalda', 'Barra'),
  ('Remo Pendlay', 'Espalda', 'Espalda', 'Barra'),
  ('Remo T-Bar', 'Espalda', 'Espalda', 'Máquina/Barra'),
  ('Remo con mancuerna unilateral', 'Espalda', 'Espalda', 'Mancuerna'),
  ('Remo con mancuernas', 'Espalda', 'Espalda', 'Mancuernas'),
  ('Remo sentado en polea', 'Espalda', 'Espalda', 'Polea'),
  ('Remo unilateral en polea', 'Espalda', 'Espalda', 'Polea'),
  ('Remo en máquina', 'Espalda', 'Espalda', 'Máquina'),
  ('Remo Hammer', 'Espalda', 'Espalda', 'Máquina'),
  ('Pullover en polea', 'Espalda', 'Espalda', 'Polea'),
  ('Pullover en máquina', 'Espalda', 'Espalda', 'Máquina'),
  ('Peso muerto convencional', 'Espalda', 'Espalda', 'Barra'),
  ('Peso muerto sumo', 'Espalda', 'Espalda', 'Barra'),
  ('Hiperextensiones', 'Espalda', 'Espalda', 'Máquina/Peso corporal'),
  ('Press militar con barra', 'Hombros', 'Hombros', 'Barra'),
  ('Press militar con mancuernas', 'Hombros', 'Hombros', 'Mancuernas'),
  ('Press Arnold', 'Hombros', 'Hombros', 'Mancuernas'),
  ('Press de hombros en máquina', 'Hombros', 'Hombros', 'Máquina'),
  ('Press unilateral en máquina', 'Hombros', 'Hombros', 'Máquina'),
  ('Elevaciones laterales', 'Hombros', 'Hombros', 'Mancuernas'),
  ('Elevaciones laterales en polea', 'Hombros', 'Hombros', 'Polea'),
  ('Elevaciones laterales en máquina', 'Hombros', 'Hombros', 'Máquina'),
  ('Elevaciones frontales', 'Hombros', 'Hombros', 'Mancuernas'),
  ('Elevaciones frontales con barra', 'Hombros', 'Hombros', 'Barra'),
  ('Elevaciones frontales en polea', 'Hombros', 'Hombros', 'Polea'),
  ('Pájaros con mancuernas', 'Hombros', 'Hombros', 'Mancuernas'),
  ('Pájaros en máquina', 'Hombros', 'Hombros', 'Máquina'),
  ('Face Pull', 'Hombros', 'Hombros', 'Polea'),
  ('Remo al mentón', 'Hombros', 'Hombros', 'Barra'),
  ('Remo al mentón con cable', 'Hombros', 'Hombros', 'Polea'),
  ('Curl con barra recta', 'Bíceps', 'Bíceps', 'Barra'),
  ('Curl con barra EZ', 'Bíceps', 'Bíceps', 'Barra'),
  ('Curl con mancuernas', 'Bíceps', 'Bíceps', 'Mancuernas'),
  ('Curl alternado con mancuernas', 'Bíceps', 'Bíceps', 'Mancuernas'),
  ('Curl martillo', 'Bíceps', 'Bíceps', 'Mancuernas'),
  ('Curl martillo cruzado', 'Bíceps', 'Bíceps', 'Mancuernas'),
  ('Curl inclinado', 'Bíceps', 'Bíceps', 'Mancuernas'),
  ('Curl concentrado', 'Bíceps', 'Bíceps', 'Mancuerna'),
  ('Curl predicador', 'Bíceps', 'Bíceps', 'Máquina'),
  ('Curl predicador con barra EZ', 'Bíceps', 'Bíceps', 'Barra'),
  ('Curl en polea baja', 'Bíceps', 'Bíceps', 'Polea'),
  ('Curl unilateral en polea', 'Bíceps', 'Bíceps', 'Polea'),
  ('Curl bayesian', 'Bíceps', 'Bíceps', 'Polea'),
  ('Curl spider', 'Bíceps', 'Bíceps', 'Mancuernas/Barra'),
  ('Curl 21', 'Bíceps', 'Bíceps', 'Barra'),
  ('Press banca agarre cerrado', 'Tríceps', 'Tríceps', 'Barra'),
  ('Fondos para tríceps', 'Tríceps', 'Tríceps', 'Peso corporal'),
  ('Extensión de tríceps en polea', 'Tríceps', 'Tríceps', 'Polea'),
  ('Extensión con cuerda', 'Tríceps', 'Tríceps', 'Polea'),
  ('Extensión unilateral en polea', 'Tríceps', 'Tríceps', 'Polea'),
  ('Extensión por encima de la cabeza', 'Tríceps', 'Tríceps', 'Polea'),
  ('Extensión francesa', 'Tríceps', 'Tríceps', 'Barra EZ'),
  ('Press francés con mancuernas', 'Tríceps', 'Tríceps', 'Mancuernas'),
  ('Extensión unilateral con mancuerna', 'Tríceps', 'Tríceps', 'Mancuerna'),
  ('Patada de tríceps', 'Tríceps', 'Tríceps', 'Mancuerna'),
  ('Patada de tríceps en polea', 'Tríceps', 'Tríceps', 'Polea'),
  ('Pressdown agarre inverso', 'Tríceps', 'Tríceps', 'Polea'),
  ('Extensión de tríceps en máquina', 'Tríceps', 'Tríceps', 'Máquina'),
  ('Fondos asistidos para tríceps', 'Tríceps', 'Tríceps', 'Máquina'),
  ('Sentadilla con barra', 'Piernas', 'Piernas', 'Barra'),
  ('Sentadilla frontal', 'Piernas', 'Piernas', 'Barra'),
  ('Sentadilla Hack', 'Piernas', 'Piernas', 'Máquina'),
  ('Sentadilla en Smith', 'Piernas', 'Piernas', 'Máquina'),
  ('Prensa 45°', 'Piernas', 'Piernas', 'Máquina'),
  ('Prensa horizontal', 'Piernas', 'Piernas', 'Máquina'),
  ('Extensión de piernas', 'Piernas', 'Piernas', 'Máquina'),
  ('Sentadilla goblet', 'Piernas', 'Piernas', 'Mancuerna'),
  ('Zancadas con mancuernas', 'Piernas', 'Piernas', 'Mancuernas'),
  ('Zancadas con barra', 'Piernas', 'Piernas', 'Barra'),
  ('Bulgarian Split Squat', 'Piernas', 'Piernas', 'Mancuernas'),
  ('Bulgarian Split Squat en Smith', 'Piernas', 'Piernas', 'Máquina'),
  ('Step Up', 'Piernas', 'Piernas', 'Mancuernas'),
  ('Sissy squat', 'Piernas', 'Piernas', 'Peso corporal/Máquina'),
  ('Peso muerto rumano', 'Piernas', 'Piernas', 'Barra'),
  ('Peso muerto rumano con mancuernas', 'Piernas', 'Piernas', 'Mancuernas'),
  ('Peso muerto piernas rígidas', 'Piernas', 'Piernas', 'Barra'),
  ('Curl femoral acostado', 'Piernas', 'Piernas', 'Máquina'),
  ('Curl femoral sentado', 'Piernas', 'Piernas', 'Máquina'),
  ('Curl femoral unilateral', 'Piernas', 'Piernas', 'Máquina'),
  ('Curl femoral de pie', 'Piernas', 'Piernas', 'Máquina'),
  ('Nordic Hamstring Curl', 'Piernas', 'Piernas', 'Peso corporal'),
  ('Buenos días', 'Piernas', 'Piernas', 'Barra'),
  ('Pull Through', 'Piernas', 'Piernas', 'Polea'),
  ('Hip Thrust', 'Piernas', 'Piernas', 'Barra'),
  ('Hip Thrust en máquina', 'Piernas', 'Piernas', 'Máquina'),
  ('Hip Thrust en Smith', 'Piernas', 'Piernas', 'Máquina'),
  ('Glute Bridge', 'Piernas', 'Piernas', 'Barra'),
  ('Glute Bridge en máquina', 'Piernas', 'Piernas', 'Máquina'),
  ('Patada de glúteo en polea', 'Piernas', 'Piernas', 'Polea'),
  ('Patada de glúteo en máquina', 'Piernas', 'Piernas', 'Máquina'),
  ('Abducción de cadera', 'Piernas', 'Piernas', 'Máquina'),
  ('Abducción en polea', 'Piernas', 'Piernas', 'Polea'),
  ('Sentadilla sumo', 'Piernas', 'Piernas', 'Barra'),
  ('Peso muerto sumo', 'Piernas', 'Piernas', 'Barra'),
  ('Zancada reversa', 'Piernas', 'Piernas', 'Mancuernas'),
  ('Elevación de talones de pie', 'Gemelos', 'Gemelos', 'Máquina'),
  ('Elevación de talones sentado', 'Gemelos', 'Gemelos', 'Máquina'),
  ('Elevación de talones en prensa', 'Gemelos', 'Gemelos', 'Máquina'),
  ('Elevación unilateral de talón', 'Gemelos', 'Gemelos', 'Mancuerna'),
  ('Elevación de talones con barra', 'Gemelos', 'Gemelos', 'Barra'),
  ('Donkey Calf Raise', 'Gemelos', 'Gemelos', 'Máquina/Peso corporal'),
  ('Calf Raise en Smith', 'Gemelos', 'Gemelos', 'Barra/Máquina'),
  ('Calf Raise unilateral en máquina', 'Gemelos', 'Gemelos', 'Máquina'),
  ('Crunch en máquina', 'Abdominales', 'Abdominales', 'Máquina'),
  ('Crunch en polea', 'Abdominales', 'Abdominales', 'Polea'),
  ('Crunch abdominal', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Crunch inverso', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Elevación de piernas', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Elevación de rodillas colgado', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Ab Wheel', 'Abdominales', 'Abdominales', 'Rueda abdominal'),
  ('Pallof Press', 'Abdominales', 'Abdominales', 'Polea'),
  ('Woodchopper', 'Abdominales', 'Abdominales', 'Polea'),
  ('Russian Twist', 'Abdominales', 'Abdominales', 'Peso corporal/Disco'),
  ('Plancha', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Plancha lateral', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Sit Up', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Mountain Climber', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Dead Bug', 'Abdominales', 'Abdominales', 'Peso corporal'),
  ('Encogimientos con barra', 'Trapecio', 'Trapecio', 'Barra'),
  ('Encogimientos con mancuernas', 'Trapecio', 'Trapecio', 'Mancuernas'),
  ('Encogimientos en Smith', 'Trapecio', 'Trapecio', 'Máquina'),
  ('Encogimientos en polea', 'Trapecio', 'Trapecio', 'Polea'),
  ('Farmer''s Walk', 'Trapecio', 'Trapecio', 'Mancuernas'),
  ('Remo al mentón', 'Trapecio', 'Trapecio', 'Barra'),
  ('Curl de muñeca', 'Antebrazos', 'Antebrazos', 'Barra'),
  ('Curl inverso de muñeca', 'Antebrazos', 'Antebrazos', 'Barra'),
  ('Curl de muñeca con mancuerna', 'Antebrazos', 'Antebrazos', 'Mancuerna'),
  ('Curl inverso con barra', 'Antebrazos', 'Antebrazos', 'Barra'),
  ('Farmer''s Walk', 'Antebrazos', 'Antebrazos', 'Mancuernas'),
  ('Wrist Roller', 'Antebrazos', 'Antebrazos', 'Barra/Disco')
) as v(name, category, muscle_group, equipment)
where not exists (
  select 1 from public.exercises e
  where e.source = 'seed' and e.created_by_trainer is null and e.name = v.name
);
